### ISSUE TITLE
坐等支持Electron

### ISSUE THREAD

**Issue by lizhuangs** [weolar/miniblink#1]
出来了，有空想玩一玩。太宠大的东东，实在是提不起来兴趣。精简小巧是王道。 出来了，先联系switchhosts的作者，把那玩意即将出来的Electron版本精简下就太棒了。

**Comment by weolar** [comment]
可以可以，敬请期待electron适配版

**Comment by RockNHawk** [comment]
我用你放出来的 minblack bracketsshell 跑我们的 Angular 2 应用，界面是正确渲染出来了，不过点击事件都失效了，electron 是正常的，有需要我可以把我们的代码发给你你调试看看，可能是对于 Angular 2 路由部分，即浏览器 hash change 部分支持有 bug。

我们就用 electron 的壳，没用里面的 API，所以应该确实是 BUG。
